[memory.flash]
size = "128K"
origin = 0x08000000

[memory.ram]
size = "32K"
origin = 0x20000000

[heap.main]
size = "10K"
pools = [
    { block = "4", capacity = 118 },
    { block = "8", capacity = 148 },
    { block = "20", capacity = 82 },
    { block = "56", capacity = 34 },
    { block = "116", capacity = 16 },
    { block = "208", capacity = 8 },
    { block = "336", capacity = 3 },
    { block = "512", capacity = 1 },
]

[linker]
platform = "riscv"

[probe]
gdb-client-command = "riscv32-unknown-elf-gdb"

[probe.jlink]
gdb-server-command = "JLinkGDBServerCLExe"
commander-command = "JLinkExe"
device = "GD32VF103CBT6"
interface = "JTAG"
speed = 4000
port = 2331
